### ISSUE TITLE
Timo bug 

### ISSUE THREAD

**Issue by timoRR9** [shigedangao/fbdev2016#5]
Warning: Invalid argument supplied for foreach() in C:\work\dev\sites\fbdev\entity\Contest.php on line 29
Call Stack
#	Time	Memory	Function	Location
1	0.0034	278624	{main}( )	..\index.php:0
2	0.0222	1100136	Slim\App->run( )	..\index.php:109
3	0.0362	1921408	Slim\App->process( )	..\App.php:293
4	0.0362	1921576	Slim\App->callMiddlewareStack( )	..\App.php:332
5	0.0362	1921672	Slim\App->Slim\{closure}( )	..\MiddlewareAwareTrait.php:116
6	0.0362	1921720	call_user_func:{C:\work\dev\sites\fbdev\vendor\slim\slim\Slim\MiddlewareAwareTrait.php:67} ( )	..\MiddlewareAwareTrait.php:67
7	0.0363	1921864	Slim\DeferredCallable->__invoke( )	..\MiddlewareAwareTrait.php:67
8	0.0369	1943392	call_user_func_array:{C:\work\dev\sites\fbdev\vendor\slim\slim\Slim\DeferredCallable.php:43} ( )	..\DeferredCallable.php:43
9	0.0369	1943912	RKA\SessionMiddleware->__invoke( )	..\DeferredCallable.php:43
10	0.0372	1946264	Slim\App->__invoke( )	..\SessionMiddleware.php:47
11	0.0431	2068344	Slim\Route->run( )	..\App.php:438
12	0.0431	2068712	Slim\Route->callMiddlewareStack( )	..\Route.php:316
13	0.0432	2069712	Slim\Route->__invoke( )	..\MiddlewareAwareTrait.php:116
14	0.0440	2095016	Slim\Handlers\Strategies\RequestResponse->__invoke( )	..\Route.php:344
15	0.0440	2095064	call_user_func:{C:\work\dev\sites\fbdev\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php:41} ( )	..\RequestResponse.php:41
16	0.0440	2095168	Closure->{closure:C:\work\dev\sites\fbdev\index.php:47-57}( )	..\RequestResponse.php:41
17	0.0633	2932568	Slim\Views\Twig->render( )	..\index.php:56
18	0.0633	2932688	Slim\Views\Twig->fetch( )	..\Twig.php:105
19	0.1360	5298112	Twig_Template->render( )	..\Twig.php:92
20	0.1360	5314824	Twig_Template->display( )	..\Template.php:411
21	0.1363	5315928	Twig_Template->displayWithErrorHandling( )	..\Template.php:403
22	0.1363	5316000	__TwigTemplate_a57d79511a789eb04ffeb51d492d6587eaf73b8c14875baad0c314378271306e->doDisplay( )	..\Template.php:432
23	0.1363	5316384	Twig_Template->display( )	..\Environment.php(458) : eval()'d code:24
24	0.1363	5317056	Twig_Template->displayWithErrorHandling( )	..\Template.php:403
25	0.1363	5317120	__TwigTemplate_16c4028ef5026997b8beceb3f83efdc8e333a5ea7482e5ca01e5179d29ca57e6->doDisplay( )	..\Template.php:432
26	0.1363	5317520	Twig_Template->displayBlock( )	..\Environment.php(458) : eval()'d code:53
27	0.1363	5317792	__TwigTemplate_a57d79511a789eb04ffeb51d492d6587eaf73b8c14875baad0c314378271306e->block_content( )	..\Template.php:215
28	0.1365	5324632	Twig_Template->getAttribute( )	..\Environment.php(458) : eval()'d code:45
29	0.1366	5327464	ContestController->getCurrentContest( )	..\Template.php:672
30	0.1366	5327536	Contest->getCurrentContest( )	..\ContestController.php:32

**Comment by shigedangao** [comment]
Tu peux te connecter à ta base et faire la commande SQL via le terminal, SELECT * FROM contest et me dire si la requête renvoie vide ou bien avec des données ?
